
title: App alunos inatel
email: victormsz09@yahoo.com.br # Your email address
description: >- # 
  Site para alunos do inatel
baseurl: "" 
url: "https://victormsz.github.io"
repository: "victormsz/AppInatel" 

# Build settings
markdown: kramdown 
theme: minima 
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# files in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
